import Head from "next/head";
import Issues from "./components/Issues";

export default function Home() {
  return (
    <>
      <Head>
        <title>GitHub Issues</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Issues />
      </main>
    </>
  );
}
